import os
os.system("pip3 install colorama")
os.system("pip3 install pysocks")
os.system("pip3 install wheel")
os.system("pip3 install fastapi")
os.system("pip3 install uvicorn")
os.system("pip3 install aiofiles")
os.system("pip3 install pydantic")
os.system("pip3 install jinja2")
os.system("pip3 install httpx")
os.system("pip3 install phonenumbers")
os.system("pip3 install click")
os.system("pip3 install sentry-sdk")
os.system("pip3 install loguru")
os.system("pip3 install random_user_agent")
os.system("pip3 install b0mb3r -U")
os.system("cd")
os.system("cd spammer")
os.system("python3 spammer.py")